### ISSUE TITLE
zip archive have changed

### ISSUE THREAD

**Issue by marc-moreaux** [mil-tokyo/bc_learning_sound#1]
Hey,

it looks like the archive have changed :/
Can you share a zip of the previous 'ESC-10/archive/master.zip' and 'ESC-50/archive/master.zip' ?

or share how the dataset should be organised such that I can replicate it ?

From What I understand, I must have a dictionnary :
``` python
dataset = {
   fold1 : {
        sounds : [ ],  # all the audio souds
        labels : [ ] }
...
}
```

**Comment by marc-moreaux** [comment]
I'm currently working on a solution which takes the git as input and revert it to ogg state

**Comment by Tokozume** [comment]
Thanks for your suggestion. That's a good idea, but we will rewrite esc-gen.py so that it works on the latest ESC datasets. Thank you!
