### ISSUE TITLE
Can't replicate ESC10's results

### ISSUE THREAD

**Issue by marc-moreaux** [mil-tokyo/bc_learning_sound#3]
Hello,

I can't replicate the results showed on the ESC-10 dataset.
 **When training envNet :** 
```shell
python main.py --dataset esc10 --netType envnet --data $DATAPATH --strongAugment --BC --split 1
```
I achieve a validation accuracy of ~15% (loss is 0.664)
![image](https://user-images.githubusercontent.com/5469621/36605470-1b034a38-18c1-11e8-9c9b-80731c573c8c.png)

---

 **And When training EnvNetV2 :** 
```shell
python main.py --dataset esc10 --netType envnetv2 --data $DATAPATH --strongAugment --BC --split 1
```
I achieve a validation accuracy of ~20% too (loss ends up at 0.587 )
![image](https://user-images.githubusercontent.com/5469621/36604037-e87ec74e-18bc-11e8-977e-b9d2cfad7aec.png)

Any idea why ?

**Comment by Tokozume** [comment]
Hello,

Split 1 is relatively difficult. Our results are the average of all splits. You can run all splits if you do not use --split command.

**Comment by marc-moreaux** [comment]
Indeed :) thx
![image](https://user-images.githubusercontent.com/5469621/36682897-8c73b9b6-1b1c-11e8-9b5b-7dfbcaa8fff8.png)
