### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by juliagusak** [mil-tokyo/bc_learning_sound#4]
Hello!

I have read the paper  https://arxiv.org/pdf/1711.10282.pdf describing  bc-learning for sound recognition. As I understand, the paper contains the graphs and tables only for training step, or am I wrong? Couldn't you, please, provide the figures with validation curves and validation error rate? Thanks!

**Comment by Tokozume** [comment]
Hello, I'm so sorry for the late reply. 

All the graphs and tables represent testing errors. Thank you.

**Comment by juliagusak** [comment]
Thank you for the answer!
